# Generated by Django 4.2.4 on 2025-11-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('participant', 'Participant'), ('ograniser', 'Organiser'), ('external', 'External')], default='patient', max_length=20),
        ),
    ]
