# Generated by Django 4.2.4 on 2025-11-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('unlimited_participants', models.BooleanField(default=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('booked_participants', models.PositiveIntegerField(default=0)),
                ('available_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='app.event')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('event', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
