# Generated by Django 4.1.13 on 2025-12-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recording'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recording',
        ),
    ]
