# Generated by Django 4.1.13 on 2025-11-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bookedevent_booking_bookedparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='parentevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parent_events/'),
        ),
    ]
