# Generated by Django 4.1.13 on 2025-12-21 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userrecording'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRecording',
        ),
    ]
