# Generated by Django 4.1.13 on 2025-12-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recording',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
