# Generated by Django 4.1.13 on 2025-12-21 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_recording_title_alter_recording_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='title',
        ),
    ]
